### ISSUE TITLE
About Training Dataset

### ISSUE THREAD

**Issue by dontLoveBugs** [rossimattia/depth-refinement-and-normal-estimation#1]
In your paper, you introduced the test dataset, but what is the training dataset to train your model?

**Comment by rossimattia** [comment]
@dontLoveBugs I think you are referring to the synthetic dataset used in training of the confidence prediction network, for our tests on the ETH3D dataset. If this is the case, that synthetic dataset is not public yet, as it refers to another publication which is currently under review.

In general, our depth refinement does not require any training and you can use the confidence you prefer.

**Comment by dontLoveBugs** [comment]
> @dontLoveBugs I think you are referring to the synthetic dataset used in training of the confidence prediction network, for our tests on the ETH3D dataset. If this is the case, that synthetic dataset is not public yet, as it refers to another publication which is currently under review.
> 
> In general, our depth refinement does not require any training and you can use the confidence you prefer.

Thanks.
